# generated by datamodel-codegen:
#   filename:  getRecentMatchHistory.json
#   timestamp: 2024-09-02T23:39:15+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Result(BaseModel):
    code: int
    message: str


class Matchhistoryreportresult(BaseModel):
    matchhistory_id: int
    profile_id: int
    resulttype: int
    teamid: int
    race_id: int
    xpgained: int
    counters: str
    matchstartdate: int


class Matchurl(BaseModel):
    profile_id: int
    url: str
    size: int
    datatype: int


class MatchhistorymemberItem(BaseModel):
    matchhistory_id: int
    profile_id: int
    race_id: int
    statgroup_id: int
    teamid: int
    wins: int
    losses: int
    streak: int
    arbitration: int
    outcome: int
    oldrating: int
    newrating: int
    reporttype: int


class MatchHistoryStat(BaseModel):
    id: int
    creator_profile_id: int
    mapname: str
    maxplayers: int
    matchtype_id: int
    options: str
    slotinfo: str
    description: str
    startgametime: int
    completiontime: int
    observertotal: int
    matchhistoryreportresults: List[Matchhistoryreportresult]
    matchhistoryitems: List
    matchurls: List[Matchurl]
    matchhistorymember: List[MatchhistorymemberItem]


class Profile(BaseModel):
    profile_id: int
    name: str
    alias: str
    personal_statgroup_id: int
    xp: int
    level: int
    leaderboardregion_id: int
    country: str


class getRecentMatchHistory(BaseModel):
    result: Result
    matchHistoryStats: List[MatchHistoryStat]
    profiles: List[Profile]
