"""
Dataclass that models the response from the `getAvailableLeaderboards` api.
Schema was found here: https://wiki.librematch.org/rlink/community/leaderboard/getAvailableLeaderboards
"""


# generated by datamodel-codegen:
#   filename:  getAvailableLeaderboards.json
#   timestamp: 2024-09-05T20:36:40+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Result(BaseModel):
    code: int
    message: str


class LeaderboardmapItem(BaseModel):
    matchtype_id: int
    statgroup_type: int
    race_id: int


class Leaderboard(BaseModel):
    id: int
    name: str
    isranked: int
    leaderboardmap: List[LeaderboardmapItem]


class MatchType(BaseModel):
    id: int
    name: str
    locstringid: int


class Race(BaseModel):
    id: int
    name: str
    faction_id: int
    locstringid: int


class LeaderboardRegion(BaseModel):
    id: int
    name: str
    locstringid: int


class getAvailableLeaderboards(BaseModel):
    result: Result
    leaderboards: List[Leaderboard]
    matchTypes: List[MatchType]
    races: List[Race]
    factions: List
    leaderboardRegions: List[LeaderboardRegion]
