"""
Dataclass that models the response from the `getRecentMatchHistory` api.
Schema was found here: https://wiki.librematch.org/rlink/community/leaderboard/getrecentmatchhistory
"""


# generated by datamodel-codegen:
#   filename:  getRecentMatchHistory.json
#   timestamp: 2024-09-02T23:39:15+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Result(BaseModel):
    code: int
    message: str


class Matchhistoryreportresult(BaseModel):
    matchhistory_id: int
    profile_id: int
    resulttype: int
    teamid: int
    civilization_id: int
    xpgained: int
    counters: str
    matchstartdate: int


class Matchurl(BaseModel):
    profile_id: int
    url: str
    size: int
    datatype: int


class MatchhistorymemberItem(BaseModel):
    matchhistory_id: int
    profile_id: int
    civilization_id: int
    statgroup_id: int
    teamid: int
    wins: int
    losses: int
    streak: int
    arbitration: int
    outcome: int
    oldrating: int
    newrating: int
    reporttype: int


class MatchHistoryStat(BaseModel):
    id: int
    creator_profile_id: int
    mapname: str
    maxplayers: int
    matchtype_id: int
    options: str
    slotinfo: str
    description: str
    startgametime: int
    completiontime: int
    observertotal: int
    matchhistoryreportresults: List[Matchhistoryreportresult]
    matchhistoryitems: List
    matchurls: List[Matchurl]
    matchhistorymember: List[MatchhistorymemberItem]


class Profile(BaseModel):
    profile_id: int
    name: str
    alias: str
    personal_statgroup_id: int
    xp: int
    level: int
    leaderboardregion_id: int
    country: str

    def __post_init__(self) -> None:
        self.steam_id = self._get_steam_id(self.name)

    def _get_steam_id(self, name: str) -> str:
        """
        From the available API, "name" is f"/steam/{STEAM_ID}"

        Returns:
            str: given "name" from the API, it returns STEAM_ID
        """
        return name.split("/")[-1]


class getRecentMatchHistory(BaseModel):
    result: Result
    matchHistoryStats: List[MatchHistoryStat]
    profiles: List[Profile]
